name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      uses: actions/checkout@v4
      with:
        repository: o0SpeedySam0o/github-actions-lab1-q1
      run: |
        pip install -r requirements.txt
